cloud-gov/deploy-logsearch

logsearch-jobs.yml
secrets.example.yml

Add the `riemann-emitter` job and merge the associated properties from secrets. See https://github.com/18F/cg-riemann-boshrelease/blob/master/jobs/riemann-emitter/spec#L26-L31.

Send elastic cluster health to riemann.

---

pipeline.yml

This is necessary now that the logsearch deploy uses a handful of jobs
from the riemann release (riemann-emitter, riemann-checklogs).

Upload riemann release on deploy.

---

pipeline.yml

Fixes a dumb mistake I made on errand names earlier.
@LinuxBozo

Pipeline cleanup

---

pipeline.yml

* Reenable shard allocation in deploy job to control order
* Notify slack on smoke test status
I noticed that the logsearch smoke tests sometimes fail after deploy, but then work when run manually. My guess is that this happens when smoke tests run before shard allocation is reenabled. This patch moves the shard allocation job into the main logsearch deploy job to ensure that it runs directly after the deploy and adds slack notifications on smoke test status.
Tagging @LinuxBozo as our official elastic expert and @datn because I thought you might be interested.

Reenable shard allocation directly after deploy.

---

logsearch-infrastructure-aws.yml
logsearch-jobs.yml

The `cluster_monitor` job runs the ingestor jobs, so it also needs the logstash s3 output patch and the logging iam role. This seems to be why we've been getting all the pages about this job failing.
@cnelson

Apply logstash patch to cluster monitor job.

---

logsearch-jobs.yml

Install and configure logstash-output-cloudwatchlogs plugin and ship logs to cloudwatch, namespaced by instance id. Requires https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/5.

Ship firehose to cloudwatch.

---

pipeline.yml

We can revert to the release on bosh.io once
https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/5
is released.
@cnelson

Build logsearch release.

---

logsearch-jobs.yml

Rest of the configuration is in secrets

Use route_registrar job from cf release to register logsearch with the go router

---

logsearch-jobs.yml

Collect additional firehose event types to populate kibana dashboards. This should fix the performance dashboard on logs.fr.cloud.gov that may be relevant to @adborden. Note--there are still more dashboards that we aren't populating--we might just want to capture all firehose events, but I'm not sure which dashboards users want to see.
Here's what we'll get with this change:

Collect container metrics from firehose.

---

README.md
pipeline.yml

Because the cf secrets should be the source of truth for platform clients and users, and because who has time to wait for bosh errands. I added the kibana client to the staging and prod cf secrets.

Drop uaa client errands.

---

logsearch-jobs.yml
pipeline.yml

No longer needed after merging
https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/19.

Drop shard allocation errand.

---

logsearch-jobs.yml

This errand isn't used anymore and should've been deleted earlier.

Drop unused errand.

---

credentials.example.yml
pipeline.yml

So that we have better visibility into outages that don't happen right after deploy.

Run smoke tests regularly.

---

logsearch-jobs.yml

Our stemcell updates take a long time, possibly because all of the compliance jobs we run, so bump the delay interval timeout to 15 minutes. Depends on https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/39; not ready for merge yet.

Configure restart delay allocation.

---

logsearch-jobs.yml

With all the other addons running on our VMs, allocating 75% (the default) of memory to kibana causes the VM to frequently use more than 90% of available memory which triggers alerts.

Decrease kibana memory allocation by 10%

---

logsearch-deployment.yml
logsearch-jobs.yml

Goes with https://github.com/18F/cg-snort-boshrelease/pull/13.

Configure snort addon via linked job.

---

logsearch-jobs.yml

Because custom config yaml is a string, not an object 😓

Fix yaml formatting.

---

README.md
logsearch-jobs.yml
logsearch-production.yml
logsearch-staging.yml
secrets.example.yml

Move more public information out of secrets and into yml in source control.
This supports updates to runbooks in https://github.com/18F/cg-site/pull/879

Move cf client IDs into public yml files

---

bosh-lint.yml
logsearch-production.yml
logsearch-staging.yml
pipeline.yml

* Fix / ignore manifest lint
* Drop top-level concourse properties, since we're not allowed to use them as of 3.2.0

Fix bosh manifest lint.

---

logsearch-jobs.yml

Tell the `upload-kibana-objects` job that we're collecting `ContainerMetrics`, and hella escape brackets to fix glob matching. We might also want to send a patch upstream to take angle brackets out of the file names.

Restore firehose events on kibana upload.

---

logsearch-jobs.yml
logsearch-production.yml
logsearch-staging.yml

AFAICT we can drop ls-router entirely--it's referred to in the smoke tests, but probably not for a good reason. Before I test this on staging, does it look right-ish @cnelson ?

Use multiple kibana instances with health check.

---

logsearch-jobs.yml

So that snort can ignore traffic from it

Maint VM needs a static ip

---

cronjobs/slow-logs.sh
logsearch-deployment.yml
logsearch-jobs.yml
pipeline.yml

Temporary solution until https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/267 is merged.

Periodically apply slow logs settings to all indices.

---

logsearch-development.yml
logsearch-jobs.yml
logsearch-production.yml
logsearch-staging.yml
pipeline.yml
smoke-tests-login.py

* Update templates for latest bosh releases.
* Drop all static IPs except for masters, which other tools depend on.
* Drop cluster monitor.
This is currently deployed to development, where the upgrade Just Worked. I think it would be worth reading up on the logstash persistent queue settings, configured at https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/ingestor_syslog/spec#L50-L70, before going to production.
To verify: check that development logsearch is receiving logs. Bonus: stop the development masters, wait a while, restart them, and verify that the logs accumulated in the persistent queues eventually reach elasticsearch.
Builds on #82.

Bump releases

---

logsearch-development.yml
logsearch-jobs.yml
pipeline.yml

So that we can break logsearch with impunity.
This is blocked for the moment by login.$SYSTEM_DOMAIN/login not working in development. We can choose to ignore that for now and disable the login smoke tests, or we can figure out why login doesn't work on dev.

[WIP] Development environment

---

logsearch-development.yml
logsearch-jobs.yml
logsearch-production.yml
logsearch-staging.yml

So that the raw firehose gets backed up to s3 again. Depends on https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/89.
@LinuxBozo @cnelson @wjwoodson

Add logstash archiver instance group.

---

logsearch-jobs.yml

Note: don't merge until logstash persistent queues are deployed on production.
Because it's not used as a queue anymore.

Rename queue to redis.

---

logsearch-elastalert.yml

We really should make the cdn broker logging not log thing like `This-thing-has.dots and spaces and dashes` which gets stemmed and split weirdly by the analyzer.

fix false positives due to analyzed fields

---

logsearch-jobs.yml
logsearch-platform-deployment.yml
logsearch-platform-development.yml
logsearch-platform-elastalert.yml
logsearch-platform-jobs.yml
pipeline.yml

Platform logsearch is like customer logsearch with a few differences:
* Kibana is exposed via elb rather than route registrar to simplify restricting to gsa network
* Use elb in front of ingestors to load-balance incoming logs
* No archiver, since cloudwatch logs will be ground truth
* No firehose-to-syslog
* Show platform dashboards rather than app logs
* Shorter retention interval
Will test on development after https://github.com/18F/cg-deploy-logsearch/pull/90 is done.

Add platform logsearch.

---

ci/check-backup.sh

Account for delay in archiver uploads to s3; logs are batched into files
and are not uploaded for a few minutes after created.

Offset backup metrics by 10 minutes.

---

logsearch-development.yml
logsearch-jobs.yml
logsearch-production.yml
logsearch-staging.yml

To avoid conflicts between logsearch deployments, and for sanity.

Use sequential static ips for masters.

---

ci/check-backup.sh

So that we can alert when we don't get logsearch backup metrics.

Emit timestamp of logsearch backup check.

---

logsearch-jobs.yml

So that we don't run two jobs that each claim ~45% of memory for heap on the same machine.

Drop elastic heap size on coordinating nodes.

---

logsearch-jobs.yml
logsearch-platform-jobs.yml

Building javascript assets can take more than five minutes and fail a
logsearch deploy.

Bump kibana post-start timeout.

---

logsearch-deployment.yml

- Leave the canary time as is, so software releases timeout as normal
- Increase the actual update timeout, so that disk migrations are allowed to finish

Increase time to allow disk migrations to finish

---

logsearch-deployment.yml
logsearch-jobs.yml
logsearch-platform-deployment.yml
logsearch-platform-jobs.yml
pipeline.yml

We have multiple elastic clusters, but because of bosh, we can only run one elastic exporter per vm. This is part of a series of patches that runs elastic exporters on the elastic vms rather than prometheus.

[WIP] Run elastic exporter on elastic vms.

---

logsearch-platform-jobs.yml

We shouldn't need so many instances after dropping log volume.

Drop platform logs instance count.

---

logsearch-development.yml
logsearch-production.yml
logsearch-staging.yml

Note: don't merge until migration to cf-deployment.

[WIP] Consume nats properties from cross-deployment link.

---

ci/pipeline.yml
credentials.example.yml

The staging secrets bucket causes confusion and so @rogeruiz suggested that I go fix that up in all our deployments.  As soon as this is approved, I will fly the pipeline for this.  The secrets files should all be copied over and ready to go.

consolidate secrets buckets and regularize naming of secrets files

---

logsearch-jobs.yml

With the current release of firehose-to-syslog, the default polling
interval spikes cpu on api instances. Until upstream fixes the issue, we
can poll at a longer interval.

Increase cloud controller polling interval.

---

cronjobs/slow-logs.sh

:eyes: https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests
Related to cloudfoundry-community/logsearch-boshrelease#125

Add Content-Type header for JSON

---

elastalert/logsearch-platform-elastalert.yml

ClamAV alerts without a signature_name are useless.

Adding signature_name checks for null

---

logsearch-jobs.yml

cloudfoundry-community/logsearch-for-cloudfoundry#319 introduced a
breaking change in the manifest, now the upload-kibana-objects job
needs a link to the cloud_controller, and authentication credentials to
kibana to upload the objects using the kibana object API.
//cc 18f/cg-private#5

added links and credentials.

---

logsearch-jobs.yml
logsearch-platform-jobs.yml

removing cloud_controller link as it's optional and broke [the build](https://ci.fr.cloud.gov/teams/main/pipelines/deploy-logsearch/jobs/deploy-logsearch-development/builds/418) due to lack of deployment reference.

adding credentials in both deployments

---

logsearch-platform-jobs.yml

This adds the elb-log-ingestor to logstash-platform
open questions I have:
- should this thing instead go on its own VM, or is there a way to put it on only one instance of the ingestor VM? we probably only need one instance running this, and while it should tolerate having 3 instances running, there's no coordination in the tool to make that particularly efficient

[Don't merge] Add elb-log-ingestor to logsearch

---

ci/pipeline.yml

[ref pipeline](https://ci.fr.cloud.gov/teams/main/pipelines/deploy-logsearch)
so this change does make any changes to the tasks themselves, it only
updates a couple triggers. however, it is a major overhaul on process.
now, in order to progress through the pipeline, every job must complete
successfully. this aligns with master-in-production deployment style
that lets us make very small, very quick changes, and when it reaches
production, it's been vetted by 3 bosh deployments and 9 different test
suites.
in order to ensure the pipeline is human-readable with a low cognitive
overhead, every job's connection is with `pipeline-tasks`.
`pipeline-tasks` is not used by every job, but it forces concourse's d3
configuration to render the pipeline in a very clean, clear, concise
method. it also …

refactored pipeline to be linear.

---

ci/pipeline.yml

these parameters were apparently added by hand to the pipeline at some point, and lost when I updated the pipeline from git.

add cf parameters

---

ci/pipeline.yml
logsearch-platform-jobs.yml

last few things on this release:
- add the elb-log-ingestor release as a parameter to the bosh call in the pipeline
- fix the spruce syntax
- correct the job name

release tweaks

---

ci/pipeline.yml
ci/smoke-tests-login.py
logsearch-jobs.yml
logsearch-platform-deployment.yml
logsearch-platform-development.yml
logsearch-platform-jobs.yml

highlights:
- move upload-kibana-objects job to the maintenance VM. That's where the reference deployment puts it, and it relies on colocation for its python dependencies
- scale dev up to 5 instances. This matches prod, and dev was running out of space after adding ELB logs (I don't anticipate the same issue in stage/development - in both cases, we have more than 10 Tb of space available)
- throttle smoke tests down to 30 minutes. while working on this, I noticed that smoke tests are frequently being queued while the last smoke test is still running. Having a smoke test always running is a PITA when working on the pipeline.
- specify what release to consume elasticsearch from - this is a reaction to an upstream change causing this error: `Failed to resolve link 'elasticsearch' with type …

Deployment fixing

---

logsearch-platform-development.yml
logsearch-platform-jobs.yml

This increases the number of ingestors for logsearch-platform. Looking at [elasticsearch's docs on improving index performance](https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-indexing-speed.html), they suggest adding workers until the cluster starts to show problems keeping up, and the cluster does not look at all unhappy right now (looking at CPU usage, GC times and counts)

Scale platform

---

logsearch-jobs.yml
logsearch-production.yml

Bring the data nodes up to 8 and the ingestors up to 5.
None, just a scaling change.

scale data and ingestion nodes to handle arbitrary spikes in customer workloads

---

ci/pipeline.yml

don't require logsearch-for-cloudfoundry release to pass platform environments 

---

ci/pipeline.yml

Turns out these are needed for logsearch-platform
None

add logsearch-for-cloudfoundry back into platform deployments

---

logsearch-platform-production.yml

We scaled the ingestors last month, but we can't get the change out because they are failing their post-starts, presumably because they're overloaded. 
This gives them longer to run their post-starts, so hopefully we can scale
None

bump healthcheck timeout in production

---

logsearch-platform-development.yml
logsearch-platform-jobs.yml

This adds 2 more data nodes to the logsearch-platform deployment in production.
The *hope* is that this will improve ingestion times, since scaling the ingestors didn't seem to help.
it also pins the number of data nodes in development to 5 (which is the current number) because that seems more than sufficient. 
None.

Moar nodes

---

logsearch-development.yml
logsearch-platform-development.yml

- Scale dev to 1 of each instance since there's essentially no traffic.
None, scaling change.

resize dev to be single instance since there's no traffic.

---

logsearch-development.yml
logsearch-platform-development.yml

Just have to fix scaling as the default replica count is 5, so we need to have enough nodes to cover that. These are small burstable nodes, so it should be fine.
None.

fixed scale due to default replica count.

---

logsearch-development.yml
logsearch-jobs.yml
logsearch-platform-development.yml
logsearch-platform-production.yml
logsearch-platform-staging.yml
logsearch-production.yml
logsearch-staging.yml

* **Does**
* Explicitly set vm types to new values - reset the vm type alias to align with AWS instance type names.
* Change vm types in _development_
* **Does Not**
* Change vm types in _staging_ or _production_
* Change scaling in _staging_ or _production_
None

vm type resets.

---

ci/pipeline.yml

- Pipeline was separated for platform and tenant logsearch. It'll be hard to use pipeline if there was no grouping.
None.

Split groups and added new groups so we don't get confused later on

---

logsearch-jobs.yml

- Stop pinning the memory usage on maintenance and archiver nodes. By not specifying a heap, the heap will be set to 46% of the available memory
none

let the job figure out how much heap based on available memory

---

ci/pipeline.yml

- remove upload objects jobs for platform jobs. They don't work, and most likely will look entirely different whenever we make them work.
None

remove jobs that have no hope of working without significant work

---

ci/pipeline.yml

The logsearch deploy currently recreates all vms on every deployment. This seems time-consuming and unnecessary so we are removing this.
none

remove recreate=true on logsearch bosh deploy as it seems unnecessary

---

logsearch-jobs.yml

Moves the total_fields config to the correct job as per: https://github.com/cloud-gov/logsearch-for-cloudfoundry/blob/7c68f7878fd3aba64f2910f25f85bb2789c35d4d/jobs/elasticsearch-config-lfc/spec#L29
None

move the total_fields limit to the correct job

---

logsearch-jobs.yml

Changes the `console.enabled` property setting from `config_options` to the dedicated property for the Kibana job.
none

move console disabling from config_options to dedicated property

---

logsearch-development.yml

I am trying to get the dev cluster unstuck. I believe the data nodes are in a bad state where they can't create replicas b/c there aren't enough on version 7.
None

add a node to try and get out of the mud

---

logsearch-development.yml

I have been unable to update the cluster b/c there is only a single version 7 of the data nodes (I think). I am hoping to get to two data nodes to get past this update.
None

try to get 2 version 7 data nodes

---

logsearch-jobs.yml

- This disables the post-start health check on data nodes. This is intended to be a temporary change to allow the scale out to go through
None

temporarily disable health check for scale out

---

logsearch-jobs.yml

It's not as bad for master nodes to swap, and disabling swap
makes non-prod nodes run out of memory starting apps up
- add swap back for master nodes
None

add swap back for master nodes

---

logsearch-platform-jobs.yml

This changeset reverts a previous change that shut off use of the swap file.  That change only mattered for `es_data` and there are no performance concerns on logs-platform.  To maintain system stability, we are removing these changes.
- Remove `swap_size` additions from earlier
None

Undo swap_size adjustment for logsearch platform

---

ci/pipeline.yml
logsearch-deployment.yml
logsearch-development.yml
logsearch-jobs.yml
logsearch-platform-deployment.yml
logsearch-platform-development.yml
logsearch-platform-jobs.yml
logsearch-platform-production.yml
logsearch-platform-staging.yml
logsearch-production.yml
logsearch-staging.yml

- Upgrades from 6.8.1 to 7.6.1 
- Prepares for a logs in staging, logs in production, and logs-platform in production deployment (data node canaries = 2 to satisfy quorum).
Closes an open POAM.

v7 upgrade. ready for prod

---

logsearch-staging.yml

This changeset removes the update block `elasticsearch_data` nodes as it is no longer needed.  We needed 2 canaries and 2 in flight to ensure the new 7.6.1 cluster would hit quorum. Once updated, we do not need this anymore.
h/t to @spgreenberg for the help with this!
- Removes the update block from the `elasticsearch_data` nodes
- None; just an update to infrastructure configuration that is already shared publicly

Remove update block from staging

---

logsearch-jobs.yml

Move query indices setting to elastic search masters as per: https://github.com/cloud-gov/logsearch-boshrelease/blob/a6a69a42237516e0abc8c2fcbed5222e0f4f2aa6/jobs/elasticsearch/spec#L118
none

move max query clause to es masters

---

ci/check-backup.sh

The API for the _search endpoint has changed. The return value now looks
different, confusing this script, and the API only returns up to 10,000
results.
Meanwhile, a _count endpoint has been introduced, which makes this
script faster and more accurate.
- Fix the script
None

fix counting in backup script

---

ci/pipeline.yml

- Add build releases for logsearch and logsearch-for-cloudfoundry in ci pipeline
- Removed release builds from https://github.com/cloud-gov/cg-deploy-bosh/pull/430
None

Add logsearch logsearch-for-cloudfoundry build releases to pipeline

---

ci/pipeline.yml

- Add missing `jobs` key in the group
none

Add missing jobs key to build-releases group

---

ci/pipeline.yml

- Adds task `run-tests` to the `build-logsearch-for-cloudfoundry-release` job to  successfully run JS tests before creating the release
None

Add task to run logsearch-for-cf js tests

---

ci/pipeline.yml

To support more robust testing in https://github.com/cloud-gov/logsearch-for-cloudfoundry, moved the test running task for `build-logsearch-for-cloudfoundry-release` into its own job so we can install devDependencies without adding those to the release.
None

Breakout run tests task into job to pass to run build-logsearch-for-cloudfoundry-release

---

logsearch-platform-development.yml
logsearch-platform-jobs.yml
logsearch-platform-production.yml
logsearch-platform-staging.yml

- drop unused redis VMs. I validated these are unused by checking flow logs in dev and production. This VM has not received a single packet on the redis port in the last week. None of the other jobs reference it either, so it's fine.
Removing unused components reduces attack surface and maintenance burden

drop unused redis VMs

---

logsearch-platform-jobs.yml

- add platform s3 upload. 
One important thing to note: we're emitting files of parsed json when we're done, so this is different from the archiver functionality. Frankly, I did this because it's easier - the existing release expects only simple key/value pairs for the options on plugins, so we have to either send the whole parsed event (what we're doing) or alter the release to support more complex configurations, since emitting just the raw line would require support for something like
```
s3 {
access_key_id => "key"
...
codec => line {
format => "%{[@raw]}"
}
}
```
this reduces the likelihood of us losing all traces of an event, but also means that we have more places that a secret might exist if leaked via logging

add platform s3 upload

---

logsearch-jobs.yml

The main goal here is to start merging old indices. This is an optimization recommended by Elasticsearch to reduce shard overhead and optimize searches.
It sounds pretty safe, but to be extra safe, we'll start with 90+ day old indices to limit the amount folks hit this. I imagine we'll keep this for now, then next Monday switch from 90 to 45, then 45 to 28 about a week later, then 14, then 7 and finally 3 (we don't want less than 3 because we want to be very sure we don't write to force-merged indices)
- force merge old indices to make them more compact and optimized. Start only with 90+ day-old indices, since merging is expensive and we want to test on less-used indices first
- switch curator to daily instead of hourly. None of our tasks need to happen more than once a day, and by …

force merge old indices

---

ci/pipeline.yml

- Removes triggers to run prod deployments automatically
No real security impact, but makes deploying to production manual and intentional

remove triggers for prod deployments

---

logsearch-platform-jobs.yml

Corresponds with https://github.com/cloud-gov/logsearch-boshrelease/pull/139
- Update jobs for Logsearch platform deployment to use specific packages for platform
None

update packages for logsearch platform

---

logsearch-platform-development.yml

- bump VM type for ES dev to t3.large
None

bump VM type for ES dev to t3.large

---

logsearch-platform-production.yml

- Update VM type for smoke-tests in logsearch platform prod to give memory headroom
None

update VM type for logsearch platform prod

---

logsearch-platform-development.yml
logsearch-platform-staging.yml

- Disable data migration from old job data store (`elasticsearch`) to new job name (`elasticsearch-platform`) data store since this is already complete in dev & stage
None

disable data migration for elasticsearch-platform job in dev and staging

---

logsearch-platform-development.yml
logsearch-platform-jobs.yml
logsearch-platform-production.yml
logsearch-platform-staging.yml

- Disable data migration in logs-platform stage & prod now that all deployments have been upgraded to use `elasticsearch-platform` data store
- Configure logs-platform stage deployment to cleanup old data in `elasticsearch`
None

disable data migration & cleanup data in stage

---

logsearch-development.yml
logsearch-jobs.yml

- change tenant logs back to be retained for 180 days in ELK
None

change tenant logs back to be retained for 180 days in ELK

---

logsearch-production.yml

- update VM type for smoke tests from t3.small to t3.medium to increase memory capacity. We are frequently getting alerts about low memory for this VM
None

update VM type for smoke tests from t3.small to t3.medium

---

logsearch-platform-jobs.yml

- Properly Indents code for platform logs so that setting log indices to read only works properly
None

fixes indentation for index_settings

---

logsearch-platform-development.yml
logsearch-platform-production.yml
logsearch-platform-staging.yml

- Configure logsearch-platform prod deployment to cleanup old data in `elasticsearch` now that data has been moved to `elasticsearch-platform`
- Disable data clean up in dev & stage since it has already run
None

Clean old prod data for original elasticsearch job name

---

logsearch-production.yml

- bump instance type to r5.xlarge for logsearch prod archiver vms because all VMs are currently running above 95% memory usage
None

bump instance type to r5.xlarge for logsearch prod archiver vms

---

ci/pipeline.yml

- add separate stemcell resources for logsearch platform so that different stemcell versions can be maintained/pinned for each environment if necessary
-
-
None

add separate stemcell resources for logsearch customer and platform 

---

logsearch-jobs.yml

- Bosh DNS is already available via runtime config
none, makes things more consistent

remove duplicated bosh dns stuff

---

logsearch-platform-production.yml

- Scale down number of ingestors back now that the platform is caught up, currently at 10, was 5
-
-
None, cost savings

Scale down number of ingestors back now that the platform is caught up

---

logsearch-jobs.yml
logsearch-platform-jobs.yml

In our tenant logs system, we have three index patterns for people to search logs on:
- `logs-app*`
- `logs-*`
- `logs-platform*`
However, only `logs-app*` makes sense for tenant logs because all the indices for logs there are named as `logs-app-DATE` (e.g. `logs-app-2023-11-02`).
In fact, if you try to use `logs*` or `logs-platform*` to search tenant logs, it doesn't work.
Also, `logs-platform*` is the correct index pattern for platform logs and likewise should be the only index pattern available there.
So this PR updates logs tenant to only have the `logs-app*` index pattern and logs platform to only have the `logs-platform*` index pattern.
None, just updating index patterns available for different log systems

Update kibana index patterns

---

logsearch-jobs.yml

We are getting shard failures in production because there are more than 100 docvalue fields in our indices and the limit is 100 by default. This PR bumps the limit to 110 to give us some headroom.
None, this setting doesn't change any access to logs, just updates a default limit for indices

bump max_docvalue_fields_search to 110

---

logsearch-jobs.yml
logsearch-platform-jobs.yml

- Split the snort alerts between logs and logs-platform
- Suppress false positives from maintenance node on localhost on 9200
-
Adds custom snort alerts to logs-platform

Split logs and logs-platform snort

---

logsearch-platform-jobs.yml

- Switch to using static ip for maintenance node on logs platform so the ip address can be used for the snort rules
-
-
IP addresses stored in runtime config

Use static ip for maintenance node

---

logsearch-deployment.yml
logsearch-jobs.yml
logsearch-platform-jobs.yml

- Switch to jammy-snort bosh release for the snort config to retire the older snort bosh release
-
-
None

Switch to jammy-snort release

---

logsearch-jobs.yml
logsearch-platform-jobs.yml

- Suppressing false positive alert coming from admin actions from the ingestor nodes, external ips will still alert.
-
-
Reduce the number of false positive alerts needing investigation

Suppressing false positive snort

---

logsearch-jobs.yml
logsearch-platform-jobs.yml

- After investigation determined these were normal maintenance traffic, still going to alert if the rule is hit from an external ip
-
-
Suppressing false snort alert

Suppress false alert snort messages

---

logsearch-development.yml

Reincarnation of #346 . Turns out we do need more memory for these data nodes because they are still periodically crashing
None

update instance type for dev data nodes from t3.large to m6i.large

---

ci/pipeline.yml

- make pipeline self-flying
None

ci: make pipeline self-flying

---

ci/pipeline.yml

- get logsearch-config before trying to use it
None

fix: get logsearch-config before trying to use it

---

ci/install-node-modules.yml

- output changes from install-node-modules
None

ci: output our changes

---

logsearch-jobs.yml

Necessary to fix observed errors in Logsearch:
```
Trying to retrieve too many docvalue_fields. Must be less than or equal to: [400] but was [445]. This limit can be set by changing the [index.max_docvalue_fields_search] index level setting
```
We did previously have to increase this value in #371 
[This behavior seems symptomatic of a bug in Kibana which is apparently resolved in version 7.11](https://github.com/elastic/kibana/issues/22897#issuecomment-738081829), but we can't update to that version due to the license changes.
Should be no security impact, just increase limit to address error

increase index.max_docvalue_fields_search index setting to 500

---

logsearch-jobs.yml
logsearch-platform-jobs.yml

- Second time we've received an alert in the last 6 months for this, just going to block the traffic based on this rule instead of alerting and investigating
- Mutes the existing `alert` rule and adds a `drop` rule with a unique identifier which is the original rule number with 3 zeroes appended to keep it out of the number sequences assigned by snort maintainers: 58741000
-
Blocks traffic instead of simply alerting

Add blocking of traffic caused by snort rule 58741

---

logsearch-jobs.yml

- bump index.max_docvalue_fields_search
None

chore: bump index.max_docvalue_fields_search

---

logsearch-jobs.yml

Reverts https://github.com/cloud-gov/cg-deploy-logsearch/pull/374
This PR excludes `ValueMetric` logs (including `cpu_entitlement`) from ingestion since they do not have org/space/app metadata so they cannot meaningfully be used or queried by users. Since these metrics aren't useful to users without the additional metadata, we should exclude them and avoid the cost of ingesting and storing them.
None, just removing unhelpful metrics from ingestion

remove value metrics from ingestion 

---

ci/smoke-tests-login.py

- need smoke-tests-login to work for new endpoint
-
-
None

smoke-tests need to pass

---

logsearch-jobs.yml

- Kibana upload objects are not pointing to correct hostname
None

Updating kibana upload to use new url for old ELK

---

ci/smoke-tests-login.py
logsearch-development.yml
logsearch-jobs.yml
logsearch-production.yml
logsearch-staging.yml

- making url waiting for deletion
-
-
None

changing name to hide until deletion

---

logsearch-platform-jobs.yml

- 30 to 365
- Will need to bump disk in a few months - Added reminders to check disk on calendar
No

bump retention

---

ci/pipeline.yml

- Adds the wazuh agent in dev for testing.
When testing is complete, the agent should be installed via the runtime config and this should be reverted.
None

add wazuh agent to dev

---

ci/pipeline.yml

- Omits bpm from the wazuh agent install as it already exists in the manifest and will conflict otherwise.
none

wazuh agent w/o bpm

---

ci/pipeline.yml

- remove obsolete test for deleted auth plugin from logsearch-for-cloudfoundry release. see https://github.com/cloud-gov/logsearch-for-cloudfoundry/pull/151
The component this code tests was deleted, so there is no security impact to deleting the test

remove obsolete test
