cloud-gov/deploy-logsearch

- logsearch-infrastructure-aws.yml
With @madhujoshi 
Part of 18F/cg-atlas#65
> Restrict to govcloud instance types

- logsearch-deployment.yml
> Adding ClamAV to the manifest. #46

- logsearch-infrastructure-aws.yml
Part of https://github.com/18F/cg-product/issues/42
> Encrypt all disks at rest

- logsearch-deployment.yml
- logsearch-jobs.yml
Part of https://github.com/18F/cg-atlas/issues/14.
> Add snort job.

- logsearch-jobs.yml
> Update job name.

- logsearch-infrastructure-aws.yml
This reverts commit 392df7687c608231fa6236f0c63e2d158446ab58.
cc @dlapiduz
> Revert "Update to r3.4xlarge"

- generate.sh
- logsearch-deployment.yml
- logsearch-hardening.yml
- logsearch-infrastructure-aws.yml
- logsearch-jobs.yml
- pipeline.yml
> Update to latest logsearch-for-cloudfoundry

- credentials.example.yml
- pipeline.yml
> Add staging logsearch.

- logsearch-jobs.yml
Part of https://github.com/18F/cg-atlas/issues/148.
> Alert on updates or deletes to elastic.

- logsearch-jobs.yml
- pipeline.yml
* Rename kibana errand to match upstream
* Check in non-sensitive configuration from secrets
* Fix build URLs
@LinuxBozo
> Update to latest upstream release.

- logsearch-hardening.yml
- logsearch-jobs.yml
- pipeline.yml
* Restore missing checklogs job
* Trigger deploys on stemcell updates
> Restore checklogs

- logsearch-jobs.yml
tested on the staging box with @cnelson to great success
> added snort suppression for cluster monitor host

- logsearch-jobs.yml
Hold off on merging until @brittag or @mogul can confirm. cc @cnelson
> [WIP] Update retention interval to match compliance requirements.

- logsearch-infrastructure-aws.yml
- 7-19% more efficient CPU
- 6GB/s greater memory throughput
- Storage is now EBS
Closes https://github.com/18F/cg-product/issues/597
> Switching to c4.xlarge

- pipeline.yml
cc: https://github.com/18F/cg-product/issues/603
> use root CA for bosh

- logsearch-infrastructure-aws.yml
This is what is currently in production after resolving the outage.
> increase master instance size

- logsearch-jobs.yml
Handle renamed and deleted jobs.
> Update templates for upstream breaking changes.

- logsearch-jobs.yml
> Only run curator on maintenance machine.

- logsearch-jobs.yml
> Handle deployment dictionary breaking change.

- logsearch-jobs.yml
Part of https://github.com/18F/cg-product/issues/673.
> Bump file descriptors.

- logsearch-jobs.yml
> Bump post-start timeout.

- logsearch-infrastructure-aws.yml
- pipeline.yml
Goes with https://github.com/18F/cg-provision/pull/206.
> Use per-environment instance profiles.

- logsearch-jobs.yml
See https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/249
> Skip platform-specific kibana objects.

- logsearch-production.yml
- logsearch-staging.yml
> Fix issues in logsearch manifest

- logsearch-jobs.yml
- logsearch-production.yml
- logsearch-staging.yml
Change network to a common resource in cloud-config
> Change logsearch network name to services

- credentials.example.yml
As long as we have example credentials and secrets around...
> Add terraform to example credentials

- logsearch-jobs.yml
Goes with https://github.com/18F/cg-deploy-bosh/pull/104
> Update errand types and profiles.

- logsearch-jobs.yml
- logsearch-production.yml
- logsearch-staging.yml
- pipeline.yml
Make use of https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/260.
> [WIP] Build releases

- bosh-lint.yml
- pipeline.yml
Lint generated manifests before deploying to staging and production.
Depends on https://github.com/18F/cg-pipeline-tasks/pull/52
> Add linter check before stage and production deploys

- logsearch-production.yml
- logsearch-staging.yml
Fixes `unsupported protocol scheme ""` errors.
lol
> Fix missing protocol errors on firehose ingestor.

- logsearch-jobs.yml
curator job runs on maint not cluster monitor
> Fix snort alerts

- logsearch-jobs.yml
See https://github.com/cloudfoundry-community/logsearch-boshrelease/commit/34969979784027a0085552af3d65f4d34c373116.
> Run elasticsearch on kibana vms.

- ci/check-backup.sh
- ci/check-backup.yml
- pipeline.yml
Emit logsearch backup metrics to prometheus pushgateway:
* Log count in elastic over last 10m
* S3 file count over last 10m
* S3 file size over last 10m
pairing with @sharms
> Add logsearch backup metrics cron job.

- ci/check-backup.sh
> Get backup dates in UTC.

- pipeline.yml
> Add passed constraints to production platform logsearch.

- pipeline.yml
> Organize the pipeline into environment groups

- logsearch-platform-elastalert.yml
- logsearch-platform-jobs.yml
Alert on ClamAV detections when sent to platform logsearch instance
> Add clamav alerts to elastalert

- logsearch-platform-development.yml
Since this is the platform side, make sure ingestor is HA, even in dev.
> Should run at least 2 ingestor for HA and make ELB worthwhile

- ci/check-backup.sh
- pipeline.yml
> Check platform logs

- logsearch-jobs.yml
- logsearch-platform-jobs.yml
> Set cluster names.

- logsearch-jobs.yml
Set elastic heap size on coordinating elastic process on kibana.
> Fix kibana elastic heap typo.

- logsearch-development.yml
- logsearch-platform-development.yml
> Use minimal instance counts for development.

- logsearch-development.yml
- logsearch-platform-development.yml
> Update static ips for dev.

- logsearch-deployment.yml
- logsearch-jobs.yml
- pipeline.yml
> Drop riemann.

- logsearch-production.yml
> Fix typo in deployment name.

- ci/pipeline.yml
> Fix task yaml paths.

- ci/pipeline.yml
Testing on staging, then will move to prod.
> Remove duplicate decryption

- elastalert/logsearch-platform-elastalert.yml
- logsearch-platform-jobs.yml
The thing that we were keying off of seems no longer to be indexed.
> update clamav alert to work

- ci/pipeline.yml
> Add prometheus hosts for dev, staging, production

- logsearch-platform-jobs.yml
self-explanatory  - I used the wrong variable name
> terraform. -> terraform_outputs.

- ci/pipeline.yml
- logsearch-deployment.yml
- logsearch-platform-deployment.yml
I added the elb-log-ingestor release to the wrong manifest
> Move elb log ingestor release

- logsearch-platform-development.yml
platform dev's ingestor has been being overwhelmed. Scaling up the ingestor should help.
> add more ingestors for platform-development

- ci/pipeline.yml
this adds triggers to the dev smoke tests based on logsearch-config
> Trigger staging

- ci/pipeline.yml
None, just fixing 18f/cg-pipeline-tasks#83
> fixed errand reference.

- logsearch-platform-jobs.yml
- update the total_fields limit for app indices
None
> set max fields

- ci/pipeline.yml
- correct parameters for bosh errand task
None
> fix errand parameters

- logsearch-development.yml
- logsearch-platform-development.yml
Accidentally made Redis in dev too small so nothing is starting, upping the size a bit to try again.
None.
> make redis bigger.

- logsearch-development.yml
- logsearch-platform-development.yml
> upgrading instance sizes.

- logsearch-development.yml
- logsearch-platform-development.yml
> kibana is too small.

- logsearch-development.yml
> missed vm type field.

- logsearch-development.yml
- logsearch-platform-development.yml
- logsearch-production.yml
- logsearch-staging.yml
Added missing fields to missing types.
None.
> added missing fields to missing types.

- logsearch-platform-jobs.yml
Adding data nodes seemed to help get us closer to caught up on ingestors. Let's try it again.
None
> more data nodes, because that seemed to help last time ¯\_(ツ)_/¯

- logsearch-jobs.yml
> set max fields for apps.

- ci/pipeline.yml
> made platform and apps parallel.

- ci/pipeline.yml
- Someone pointed the flow incorrectly so fixing it for platform staging + platform production
None.
> Fixed flow for platform

- logsearch-platform-production.yml
- logsearch-platform-staging.yml
- logsearch-production.yml
- logsearch-staging.yml
Bring everything up to the most recent generation of the same instance type.
None.
> upgrading to current generations

- logsearch-platform-production.yml
> increasing size of box due to memory issues.

- logsearch-platform-production.yml
- logsearch-production.yml
Emergency swap for more disk space.
None.
> changed out for more ephemeral disks.

- logsearch-platform-staging.yml
> added smoke tests type.

- logsearch-platform-production.yml
> adding smoke tests type.

- logsearch-production.yml
- Make the production maintenance vm bigger. It's currently using all its RAM
None
> bigger maintenance vm in production

- logsearch-jobs.yml
Increases the number of data nodes from 8 to 9
none
> add a data node

- logsearch-jobs.yml
> revert to 8 data nodes

- logsearch-platform-jobs.yml
- remove ELB log ingestor 
None
> remove elb-log-ingestor

- ci/pipeline.yml
- logsearch-platform-deployment.yml
- finish removing the elb ingestor
None
> remove the rest of the elb ingestor references

- logsearch-development.yml
- Reduce the log retention period in dev to 90 days.
- Temporarily add data nodes to hopefully allow v7 update to proceed. I am currently blocked b/c we have unassigned shards and only a single data node on v7 (no place to put replicas).
none
> Reduce log retention in dev and increase data nodes

- logsearch-development.yml
Remove duplicate maintenance sections
None
> Remove duplicate maintenance sections

- logsearch-development.yml
The scale up was temporary to overcome an indexing hurdle. It should be ok to scale this back down.
None
> scale dev back down as the scale up was temporary

- logsearch-development.yml
Trying to get multiple version 7 data nodes so that replicas can be fulfilled.
none
> set 0 canaries to force multiple v7 data nodes

- ci/pipeline.yml
- logsearch-deployment.yml
- logsearch-development.yml
- logsearch-jobs.yml
- logsearch-platform-deployment.yml
- logsearch-platform-development.yml
- logsearch-platform-jobs.yml
> Undo v7 stuff

- ci/pipeline.yml
Separates dev into its own branch for this repo
none
> separate dev onto its own branch

- logsearch-jobs.yml
- scale prod
- disable query cache
None
> Scale prod

- logsearch-jobs.yml
- only increase to nine instances, since the tenth is blocked by IP addressing issues that we don't want to solve today
None
> scale down to nine so we don't have to solve IP addressing issues today

- logsearch-jobs.yml
- double the max payload
makes kibana work. Also makes kibana use more resources
> double max payload

- ci/pipeline.yml
- remove passed parameter on correct resource
None
> remove passed parameter on correct resource

- ci/pipeline.yml
- logsearch-development.yml
- logsearch-platform-development.yml
- logsearch-platform-jobs.yml
- logsearch-platform-production.yml
- logsearch-platform-staging.yml
- logsearch-production.yml
- logsearch-staging.yml
Reverts cloud-gov/cg-deploy-logsearch#233
None
> Revert "Upgrade to v7"

- logsearch-jobs.yml
Adds the disable_post_start property back in
None
> add disable_post_start back in

- logsearch-development.yml
Increases the data node instance size. JVM is unable to start on the data nodes due to insufficient memory.
none
> increase vm data node size

- logsearch-jobs.yml
Increases query size to address prod issue: 'field expansion matches too many fields, limit: 1024'
none
> increase query size

- logsearch-jobs.yml
Add the max_clause_count to the data nodes (in addition to masters)
none
> add max_clause_count to data nodes

- ci/smoke-tests-login.py
- Home is where all the kibana cookies are <3
None
> Changed login url to home

- logsearch-jobs.yml
- logsearch-platform-jobs.yml
- update settings to match component template updates in logsearch-boshrelease and logsearch-for-cloudfoundry
None
> add settings for updated logsearch-for-cloudfoundry stuff

- ci/pipeline.yml
- use the same named resources for the same conceptual resources
None
> unify release tarballs so the pipeline makes more sense

- logsearch-production.yml
- more ingestors. CF says we should have 1 firehose consumer for every traffic controller
None
> scale ingestors

- ci/pipeline.yml
- logsearch-platform-development.yml
- Pipeline has bionic
- Platform Dev to bionic
None, Bionic is cooler
> Updated pipeline and files to change platform dev to bionic

- logsearch-platform-deployment.yml
- logsearch-platform-production.yml
- logsearch-platform-staging.yml
- Removed stemcell default from base deployment to their environment
None
> Removed duplicate stemcell defaults

- ci/pipeline.yml
- logsearch-platform-staging.yml
- logsearch-staging.yml
- updating deployment to use bionic in staging
Switching from xenial to bionic helps to close CVEs
> changes for bionic in staging

- ci/pipeline.yml
- logsearch-production.yml
- logsearch-staging.yml
- Fix order in env files for bosh-lint
- Updated pipeline to final config
N/A
> Bionic fix

- logsearch-platform-production.yml
- logsearch-production.yml
- Move prod to Bionic
Moving to Bionic from Xenial closes out some CVEs
> moving prod to bionic

- logsearch-jobs.yml
> double csv report size

- logsearch-jobs.yml
- Doubled maxPayloadBytes
None
> bumped maxPayloadBytes

- logsearch-jobs.yml
- logsearch-platform-jobs.yml
- set log4j options
reduce potential for RCE from log4j
> set log4j options

- logsearch-jobs.yml
- logsearch-platform-jobs.yml
- fix dash and caps
fix params
> fix dash and caps

- ci/pipeline.yml
> call right opsfile

- logsearch-deployment.yml
> bosh links address was giving dns and we need ip for elasticsearch

- logsearch-platform-deployment.yml
- dont use dns for links 
-
-
None
> use ips for bosh links

- logsearch-platform-westb.yml
> opslogin for westb kibana

- logsearch-platform-westb.yml
> Variables dont work well with lint

- ci/pipeline.yml
- logsearch-easta.yml
- logsearch-eastb.yml
- logsearch-platform-easta.yml
- logsearch-platform-eastb.yml
- logsearch-platform-westc.yml
- logsearch-westc.yml
- Add configs for westc and eastb
-
None
> Westc eastb

- ci/pipeline.yml
- nats-tls-easta.yml
- nats-tls-eastb.yml
- nats-tls-westc.yml
> added missing nats files

- logsearch-platform-easta.yml
- logsearch-platform-eastb.yml
- logsearch-platform-westc.yml
> adding oauth creds for new regions

- logsearch-platform-jobs.yml
> correct temp dir path

- logsearch-jobs.yml
- logsearch-platform-jobs.yml
- logsearch-platform-production.yml
- clean up unused and invalid variables
None
> Clean up stuff

- logsearch-jobs.yml
- disable explicit garbage collection
- clean up old unused variable
None
> disable explicit garbage collection

- logsearch-jobs.yml
Signed-off-by: Chris McGowan <christopher.r.mcgowan@gsa.gov>
- Adding back missing log4j options 
n/a
> Adding backing missing log4j options

- logsearch-jobs.yml
> more logsearch nodes

- ci/pipeline.yml
- PGP git
- Slack Noise
-
None
> Git PGP and Slack

- logsearch-platform-jobs.yml
- Fix link names in BOSH logsearch platform jobs
None
> fix link names

- logsearch-jobs.yml
- logsearch-platform-development.yml
- logsearch-platform-jobs.yml
- enable data migration for logs-platform in dev
None
> enable data migration for logs-platform in dev

- logsearch-platform-jobs.yml
- update ES platform data nodes to migrate data
None
> update ES data nodes to migrate data

- logsearch-platform-development.yml
- logsearch-platform-production.yml
- Increase timeout for Elasticsearch migration on elasticsearch_data nodes for logsearch-platform in prod
- Deleted migrated data from Elasticsearch nodes for logsearch-platform in dev
None
> update deploy config

- logsearch-jobs.yml
- logsearch-platform-jobs.yml
- Makes logs read only after a day
Improves security by making logs read only
> Make logs read only after a specified set of time

- ci/pipeline.yml
- update name of stemcell files to match resource
None
> update name of stemcell files to match resource

- logsearch-platform-deployment.yml
> update canaries for logs-platform to 2

- logsearch-platform-deployment.yml
- logsearch-platform-development.yml
- logsearch-platform-staging.yml
> update canaries & max_in_flight for logs-platform dev & staging

- logsearch-development.yml
- logsearch-platform-development.yml
- logsearch-platform-production.yml
- logsearch-platform-staging.yml
- logsearch-production.yml
- logsearch-staging.yml
- Stemcell will us `os` instead of name
None
> stemcell name to os

- ci/check-backup.yml
- ci/pipeline.yml
- Update pipeline and script to use hardened containers
Hardened containers are more secure
> Update to use hardened containers

- ci/pipeline.yml
- logsearch-platform-production.yml
- Logs platform production jammified
None
> Logsearch Production Jammy

- logsearch-jobs.yml
- Bumping maxPayload to 6MB from 4MB
-
-
None
> Increasing maxPayload to 6MB

- logsearch-jobs.yml
- DocValue is now 200 and below 9000
None
> bump docvalu to 200

- logsearch-deployment.yml
- logsearch-platform-deployment.yml
- Add jammy-snort to list of releases
-
-
None
> Add jammy-snort to list of releases

- logsearch-jobs.yml
- logsearch-platform-jobs.yml
> sig_id != sid_id

- logsearch-jobs.yml
- logsearch-platform-jobs.yml
- After investigation determined these were normal maintenance traffic, still going to alert if the rule is hit from an external ip
-
-
Suppressing false snort alert
> Suppressing false snort alert 41495

- logsearch-platform-production.yml
- logsearch-production.yml
- logsearch-staging.yml
- Swapping 5 series for 6i series instance types
- Swapping maintenance nodes from t to m series for consistent performance (cost diff is very small)
-
-
None
> Switching to 6i series

- logsearch-jobs.yml
- Hit the limit on today's index, made the change manually through the UI, this change makes it permanent
-
-
None
> Bumping max_docvalue_fields_search

- logsearch-jobs.yml
- merge younger indices, like we said we would in #295 
-
-
None
> merge younger indices

- ci/pipeline.yml
- don't check s3 resources that only we publish to
None
> don't check s3 resources that only we publish to

- ci/install-node-modules.yml
- ci/pipeline.yml
- build node_modules into release
None
> ci: build node_modules into release

- ci/install-node-modules.yml
- add nvm commands so we use the right node versions
None
> ci: add nvm commands so we use the right node versions

- ci/pipeline.yml
- add reconfigure job to group
- move secrets resource to be a resource, not a resource_type
None
> ci: fix pipeline

- ci/pipeline.yml
- Update to use hardened images
-
-
Using hardened images
> update to hardened images

- ci/pipeline.yml
- test with declared node version, too
None
> ci: test with declared node version, too

- ci/install-node-modules.yml
- ci/pipeline.yml
-  source profile before using nvm
None
> fix: source profile before using nvm

- ci/install-node-modules.yml
- ci/pipeline.yml
- replace `source` with `.`
None
> fix: replace `source` with `.`

- ci/install-node-modules.yml
- use npm clean-install for cleaner installs
None
> ci: use npm clean-install for cleaner installs

- ci/install-node-modules.yml
- use newer npm when installing node modules
None
> fix: use newer npm when installing node modules

- .github/workflows/security-considerations.yml
- .gitignore
- .pre-commit-config.yaml
- CODEOWNERS
- LICENSE.md
- README.md
- ci/check-backup.sh
- ci/check-backup.yml
- ci/install-node-modules.yml
- ci/pipeline.yml
- ci/smoke-tests-login.yml
- credentials.example.yml
- cronjobs/slow-logs.sh
- docs/platform.puml
- docs/tenant.puml
- logsearch-deployment.yml
- logsearch-development.yml
- logsearch-jobs.yml
- logsearch-platform-deployment.yml
- logsearch-platform-development.yml
- logsearch-platform-jobs.yml
- logsearch-platform-production.yml
- logsearch-platform-staging.yml
- logsearch-production.yml
- logsearch-staging.yml
- nats-tls-dev.yml
- nats-tls-prod.yml
- nats-tls-stage.yml
- secrets.example.yml
- Add pre-commit
- apply shellcheck + yamllint suggestions
None
> chore: add pre-commit + lint everything

- logsearch-jobs.yml
- update Firehose configuration to include ValueMetric logs, including the new `cpu_entitlement` metric
None, just improving observability by adding new, better metric for tracking observability
> update Firehose configuration to include ValueMetric logs

- logsearch-jobs.yml
- Docvalue bump because we hit the limit again
None
> bump docvalue

- logsearch-development.yml
- logsearch-staging.yml
- updating uri to deprecated so opensearch can take them
-
-
None
> updating logsearch

- logsearch-production.yml
- getting prod ready for tommorow
-
-
None
> prod for tommorow

- ci/pipeline.yml
- logsearch-platform-development.yml
- Loads common variables from wazuh-agent repo for dev.
- Adds ephemeral disk to the elasticsearch_master in dev only to accomadate the wazuh-agent
- None. Not sensitive.
> load vars from shared file for env

- ci/pipeline.yml
- Trigger deploy in dev on new wazuh-agent release
None
> trigger on new wazuh agent release

- logsearch-platform-development.yml
- logsearch-platform-jobs.yml
- we use bosh links for clustering so dont need to dock on ips hopefully
-
-
yup
> Testing no static ips

- logsearch-platform-staging.yml
- I think this is causing issues in staging
-
-
None
> why are we updating half the nodes?

- logsearch-platform-jobs.yml
- to match new roles and no more legacy
None
> Add roles to remove legacy assignment

- .gitignore
- ci/pipeline.yml
- Update channel used for Slack notifications
None. These changes are not sensitive.
> Update slack channel

- logsearch-platform-production.yml
- Warm is slow so less canary
None
> Less canaries for warm since they are slower

- logsearch-platform-jobs.yml
- Data is migrated so reducing nodes and going to balance more after
None
> Reduce non-warm nodes

- logsearch-platform-jobs.yml
- Last scale down to normal data nodes
-
-
None
> Logsearch platform is able to scale down now

- logsearch-platform-development.yml
- The one dev isnt being used and we set it for all environments in different environment
None
> Remove bad vm extension
